#$ -cwd
#$ -q Annotation-1
#$ -pe mpi 2
#$ -S /bin/bash

module load Anaconda3/v2019.10
module load FastQC/v0.11.8

SAMPLE=${PWD##*/}
FILEPATH=../../raw/${SAMPLE}
INFILE1=$(ls ${FILEPATH}/*_1.fastq.gz)
INFILE2=$(ls ${FILEPATH}/*_2.fastq.gz)
FILEROOT1=${INFILE1##*/}
FILEROOT2=${INFILE2##*/}
OUTFILE1=${FILEROOT1%.fastq.gz}.QC.fastq.gz
OUTFILE2=${FILEROOT2%.fastq.gz}.QC.fastq.gz

cutadapt -j $NSLOTS \
-q 30 \
-o $OUTFILE1 \
-p $OUTFILE2 \
$INFILE1 \
$INFILE2

fastqc -t $NSLOTS *.QC.fastq.gz
