#$ -cwd
#$ -pe mpi 40
#$ -q Annotation-3
#$ -S /bin/bash

module load Anaconda3/v2019.10
module load samtools/v1.10
module load bcftools/v1.10.2
module load Bedtools2/v2.27.1

# Note that sample CC-2932 is still missing

bamboozle.py barcode --primer_size 21 --window_size 500 \
-f ../../01_mapping/Reference/C_reinhardtii_v5.5_reference.unmasked.fasta \
-b ../../02_variantcalling/CC-2343/CC-2343_sorted.bam \
../../02_variantcalling/CC-2344/CC-2344_sorted.bam \
../../02_variantcalling/CC-2936/CC-2936_sorted.bam \
../../02_variantcalling/CC-2937/CC-2937_sorted.bam \
../../02_variantcalling/CC-3065/CC-3065_sorted.bam \
../../02_variantcalling/CC-3071/CC-3071_sorted.bam \
../../02_variantcalling/CC-3076/CC-3076_sorted.bam \
../../02_variantcalling/CC-3086/CC-3086_sorted.bam \
--ploidy haploid -o Chlamy_p21_w500_mt_plus -t $NSLOTS -v --dev
